config/routes.rb
EmoticodeRails::Application.routes.draw do
  root 'home#index'

  namespace :api do
    namespace :v1 do
      
      controller :sources do
        post 'sources/new' => :create, as: :create_source
      end
      # resources :languages, :only => [ :index, :show ]
      # resources :sources
      # resources :users,     :only => [ :index, :show ]
    end
  end

  namespace :blog do
    root 'index#show'

    controller :categories do
      get ':category' => :archive, as: :archive, constraints: { category: Patterns::ROUTE_PATTERN }
    end

    controller :posts do
      get  ':category/:name.html' => :show, as: :show_post, constraints: { category: Patterns::ROUTE_PATTERN, name: Patterns::ROUTE_PATTERN }      
      get  ':category/new'        => :new,  as: :new_post, constraints: { category: Patterns::ROUTE_PATTERN }
      post ':category/create'     => :create,  as: :create_post, constraints: { category: Patterns::ROUTE_PATTERN }

      get   'post/edit/:id'    => :edit,    as: :post_edit,    constraints: { id: Patterns::ID_PATTERN }
      get   'post/destroy/:id' => :destroy, as: :post_destroy, constraints: { id: Patterns::ID_PATTERN }
      patch 'post/update/:id'  => :update,  as: :post_update,  constraints: { id: Patterns::ID_PATTERN }
    end
  end

  controller :home do
    get 'new'      => :recent,   as: :recent_snippets
    get 'trending' => :trending, as: :trending_snippets
  end

  controller :sitemaps do
    get 'sitemap_index'          => :index,     as: :sitemap_index
    get 'sitemap_snippets-:page' => :snippets,  as: :sitemap_snippets, constraints: { page: Patterns::ID_PATTERN }
    get 'sitemap_languages'      => :languages, as: :sitemap_languages
    get 'sitemap_posts'          => :posts,     as: :sitemap_posts
  end

  controller :sessions do
    get    'sign_in'  => :new,     as: :sign_in
    post   'sign_in'  => :create
    delete 'sign_out' => :destroy, as: :sign_out
  end

  controller :user do
    get  'sign_up'        => :new,     as: :sign_up
    post 'sign_up'        => :create
    get  'confirm/:token' => :confirm, as: :confirm, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  get '/auth/:provider/callback' => 'sessions#create'

  controller :favorite do
    post 'fav/:id'   => :make,    as: :favorite,   constraints: { id: Patterns::ID_PATTERN }
    post 'unfav/:id' => :destroy, as: :unfavorite, constraints: { id: Patterns::ID_PATTERN }
  end

  controller :follows do
    post 'follow/:type/:id'   => :follow,   as: :follow,   constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }
    post 'unfollow/:type/:id' => :unfollow, as: :unfollow, constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }    
  end

  controller :profile do
    get   'profile/snippets'    => :snippets,  as: :user_snippets
    get   'profile/favorites'   => :favorites, as: :user_favorites   
    get   'profile/edit'        => :edit, as: :user_settings
    patch 'profile/update'      => :update
    get   'profile/:username'   => :show, as: :user_profile, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/:username/following' => :following, as: :user_following, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/:username/followers' => :followers, as: :user_followers, constraints: { username: Patterns::USERNAME_PATTERN }    
    get   'profile/destroy/:id' => :destroy, as: :user_delete, constraints: { id: Patterns::ID_PATTERN }
    get   'profile/ban/:id'     => :ban, as: :user_ban, constraints: { id: Patterns::ID_PATTERN }    
    get   'profile/unban/:id'   => :unban, as: :user_unban, constraints: { id: Patterns::ID_PATTERN }        
    get   'badge/:username'     => :badge, as: :user_badge, constraints: { username: Patterns::USERNAME_PATTERN }
  end

  controller :search do
    get 'search(/:what)' => :search, as: :search, :constraints => {:what => /.*/}
  end

  resource :comments
  resource :votes

  resource :passwords, :only => [:new, :create]
  controller :passwords do
    get  'recovery/:token' => :edit, as: :recovery, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
    post 'recovery/:token' => :update, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  controller :feeds do
    get 'feed'                   => :feed,     as: :feed
    get '/stream/:username'      => :stream,   as: :stream_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'feed/blog'              => :blog,     as: :blog_feed
    get 'feed/:language'         => :language, as: :language_feed, constraints: { language: Patterns::ROUTE_PATTERN }
    get 'profile/:username/feed' => :user,     as: :user_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'randomfeed'             => :random,   as: :random_feed
  end

  controller :page do
    get  'about.html'   => :about,   as: :about_page
    get  'sitemap.html' => :sitemap, as: :sitemap_page
    get  'contact.html' => :contact, as: :contact_page
  end

  controller :language do
    get ':name/',    to: :archive, as: :language_archive, constraints: { name: Patterns::ROUTE_PATTERN }
  end

  controller :source do
    get   'source/new'         => :new,     as: :source_new
    post  'source/create'      => :create,  as: :source_create
    get   'source/edit/:id'    => :edit,    as: :source_edit,   constraints: { id: Patterns::ID_PATTERN }
    get   'source/destroy/:id' => :destroy, as: :source_delete, constraints: { id: Patterns::ID_PATTERN }
    patch 'source/update/:id'  => :update,  as: :source_update, constraints: { id: Patterns::ID_PATTERN }

    get 'source/:id'                             => :show,  as: :source_shortlink,     constraints: { id: Patterns::ID_PATTERN }
    get ':language_name/:source_name.html'       => :show,  as: :source_with_language, constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.txt'        => :raw,   as: :raw_with_language,    constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get 'embed/:language_name/:source_name.html' => :embed, as: :source_embed,         constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }    
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many   :comments, -> { where :commentable_type => Comment::COMMENTABLE_TYPES[:post] }, :foreign_key => :commentable_id

  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: { :minimum => 5, :maximum => 255 }
  validates :body, presence: true, length: { :minimum => 25 }

  before_create :create_name # create unique cached slug

  def self.find_by_name_and_category_name!( name, c_name )
    Post
    .joins( :category )
    .where( :categories => { name: c_name } )
    .where( :posts   => { name: name } )
    .first!
  end

  def commentable_type
    Comment::COMMENTABLE_TYPES[:post]
  end

  def url
    "http://www.emoticode.net/blog/#{category.name}/#{name}.html"
  end

  include ActionView::Helpers::SanitizeHelper

  def description!( html = false )
    Rails.cache.fetch "post_#{id}_description!_#{html}_#{title}" do
      text = body

      require 'redcarpet'

      renderer   = Redcarpet::Render::HTML.new
      extensions = {
        :fenced_code_blocks => true,
        :autolink => true,
        :underline => true,
        :quote => true,
        :footnotes => true
      }
      redcarpet  = Redcarpet::Markdown.new(renderer, extensions)

      text = redcarpet.render text

      if html
        text
      else
        strip_tags text
      end
    end
  end

  def parse!
    Rails.cache.fetch "post_#{id}_parse!_#{updated_at}" do
      require 'redcarpet'

      renderer   = Redcarpet::Render::HTML.new
      extensions = {
        :fenced_code_blocks => true,
        :autolink => true,
        :underline => true,
        :quote => true,
        :footnotes => true
      }
      redcarpet  = Redcarpet::Markdown.new(renderer, extensions)
      redcarpet.render body
    end
  end

  private

  def create_name
    base_name = title.parameterize
    name = base_name
    counter = 2
    # even if the title is validate for its uniqueness, different
    # titles could be converted to the same slug due to transliterations,
    # therefore we have to make sure that the slug is unique too.
    while Post.find_by_name(name).nil? == false
      name = "#{base_name}-#{counter}"
      counter += 1
    end

    self.name = name
  end

end

app/controllers/blog/categories_controller.rb
class Blog::CategoriesController < ApplicationController
  def archive
    @category = Category.find_by_name! params[:category] 
    @posts    = @category.posts.order('created_at DESC').all
  end
end

app/controllers/blog/index_controller.rb
class Blog::IndexController < ApplicationController
  def show
    @posts = Post.order('created_at DESC').all 
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  before_filter :authenticate!,  only: [ :new, :create, :edit, :update, :destroy ]  
  before_filter :admin!, only: [ :new, :create, :edit, :update, :destroy ]

  def show
    @post = Post.find_by_name_and_category_name! params[:name], params[:category] 
    @comment = Comment.new
  end

  def new
    @post = Post.new 
    @category = Category.find_by_name! params[:category]    
  end

  def create
    @category = Category.find_by_name! params[:category]
    
    params[:post] = params[:post].merge(:user_id => @current_user.id, :category_id => @category.id )

    @post = Post.create post_params
    if @post.valid?
      redirect_to blog_show_post_path( :category => @category.name, :name => @post.name )
    else
      flash[:error] = @post.errors.full_messages
      redirect_to blog_new_post_path( :category => @category.name )
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes( post_params )
      redirect_to blog_show_post_path( :category => @post.category.name, :name => @post.name )
    else
      flash[:error] = @post.errors.full_messages
      redirect_to blog_post_edit_path(:id => @post.id)
    end 
  end

  def destroy
    @post = Post.find params[:id] 
    @post.destroy
    redirect_to '/blog/'
  end

  private

  def admin!
    if @current_user.is_admin? == false
      redirect_to root_url
    end
  end

  def post_params
    params.require(:post).permit( :user_id, :category_id, :title, :body ) 
  end 
end

app/helpers/blog/categories_helper.rb
module Blog::CategoriesHelper
  include SeoHelper

    def html_truncate(input, num_words = 15, truncate_string = "...")
    doc = Nokogiri::HTML(input)

    current = doc.children.first
    count = 0

    while true
      # we found a text node
      if current.is_a?(Nokogiri::XML::Text)
        count += current.text.split.length
        # we reached our limit, let's get outta here!
        break if count > num_words
        previous = current
      end

      if current.children.length > 0
        # this node has children, can't be a text node,
        # lets descend and look for text nodes
        current = current.children.first
      elsif !current.next.nil?
        #this has no children, but has a sibling, let's check it out
        current = current.next
      else 
        # we are the last child, we need to ascend until we are
        # either done or find a sibling to continue on to
        n = current
        while !n.is_a?(Nokogiri::HTML::Document) and n.parent.next.nil?
          n = n.parent
        end

        # we've reached the top and found no more text nodes, break
        if n.is_a?(Nokogiri::HTML::Document)
          break;
        else
          current = n.parent.next
        end
      end
    end

    if count >= num_words
      unless count == num_words
        new_content = current.text.split

        # If we're here, the last text node we counted eclipsed the number of words
        # that we want, so we need to cut down on words.  The easiest way to think about
        # this is that without this node we'd have fewer words than the limit, so all
        # the previous words plus a limited number of words from this node are needed.
        # We simply need to figure out how many words are needed and grab that many.
        # Then we need to -subtract- an index, because the first word would be index zero.

        # For example, given:
        # <p>Testing this HTML truncater.</p><p>To see if its working.</p>
        # Let's say I want 6 words.  The correct returned string would be:
        # <p>Testing this HTML truncater.</p><p>To see...</p>
        # All the words in both paragraphs = 9
        # The last paragraph is the one that breaks the limit.  How many words would we
        # have without it? 4.  But we want up to 6, so we might as well get that many.
        # 6 - 4 = 2, so we get 2 words from this node, but words #1-2 are indices #0-1, so
        # we subtract 1.  If this gives us -1, we want nothing from this node. So go back to
        # the previous node instead.
        index = num_words-(count-new_content.length)-1
        if index >= 0
          new_content = new_content[0..index]
          current.content = new_content.join(' ') + truncate_string
        else
          current = previous
          current.content = current.content + truncate_string
        end
      end

      # remove everything else
      while !current.is_a?(Nokogiri::HTML::Document)
        while !current.next.nil?
          current.next.remove
        end
        current = current.parent
      end
    end

    # now we grab the html and not the text.
    # we do first because nokogiri adds html and body tags
    # which we don't want
    doc.root.children.first.inner_html
  end

  def page_title
    "Blog - #{@category.title} | emoticode" rescue super
  end

  def metas
    make_seo do |seo|
      seo.description = paged "#{@category.title} blog archive."
    end
  end
end

app/helpers/blog/index_helper.rb
module Blog::IndexHelper
  include SeoHelper

  def page_title
    "Blog | emoticode" rescue super
  end
end

app/helpers/blog/posts_helper.rb
module Blog::PostsHelper
  include SeoHelper

  def page_title
    "#{@post.title} | emoticode" rescue super
  end

  def metas
    make_seo do |seo|
      unless @post.id.nil?
        seo.title       = paged @post.title
        seo.description = paged truncate( @post.description!, :length => 250 )
      end
    end
  end
end

app/helpers/blog_helper.rb
module Blog::BlogHelper
  include SeoHelper

  def page_title
    raise "OK"
    "Blog | emoticode" rescue super
  end
end

app/views/blog/posts/_form.html.erb
<div id="post-<%= action %>" class="headblock">
  <%= form_for @post, :url => {:controller => 'posts', :action => action }, :html => { :class => 'pure-form pure-form-aligned' } do |f| %>
    <% @post.errors.full_messages.each do |msg| %>
      <p class="error"><%= msg %></p>
    <% end %>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <p class="error"><%= error %></p>
      <% end %>
    <% end %>

    <div class="head">
      <%= f.text_field :title, :placeholder => 'Title', :class => 'title' %>
    </div>

    <%= f.text_area :body, :placeholder => 'Text', :id => 'post_text', :style => 'display:none' %>
    <div id="epiceditor"></div>
    <%= f.submit "Save", :class => 'pure-button pure-button-primary' %>
  <% end %>
</div>
<script>
  $('#source_description').hide();
  var editor = new EpicEditor({
    textarea: 'post_text',
    basePath: '/epiceditor',
    clientSideStorage: false,
    autogrow: true,

    theme: {
      base: '/themes/base/epiceditor.css',
      preview: '/themes/preview/github.css',
      editor: '/themes/editor/emoticode.css'
    }
  }).load();
</script>

app/views/blog/posts/_listing.html.erb
<li>
<div class="post">
  <h5><%= link_to post.title, blog_show_post_path( :category => post.category.name, :name => post.name ) %></h5>
  <small>
    Posted by <%= link_to post.user.username, user_profile_path(username:post.user.username) %> inside <%= link_to post.category.title, blog_archive_path(:category => post.category.name ) %> <%= time_ago_in_words post.created_at %> ago
  </small>
  <p>
  <%=raw truncate( post.description!, :length => 400 ).gsub /&amp;/, '&' %>
  </p>
</div>
</li>

app/views/blog/posts/edit.html.erb
<%= render :partial => 'form', :locals => { action: 'update' } %>

app/views/blog/posts/new.html.erb
<%= render :partial => 'form', :locals => { action: 'create' } %>

app/views/blog/posts/show.html.erb
<section id="blog">
  <div class="medium-column">
    <div class="headblock post post-show">
      <h1><%= @post.title %></h1>
      <div class="meta">
        <a href="<%= user_profile_path(username:@post.user.username) %>" title="<%= @post.user.username %> profile" class="avatar">
          <%= image_tag image_url(@post.user.avatar), :height => '30', :width => '30', :alt => "#{@post.user.username} avatar.", :class => 'imgavatar', :onerror => "this.src='#{image_url("/avatars/default.png")}';" %>
        </a>
        <small>Posted <%= time_ago_in_words @post.created_at %> ago inside the <%= link_to @post.category.title, blog_archive_path(:category => @post.category.name ) %> category.</small><br/>
        <small>Written by <%= link_to @post.user.username, user_profile_path(username:@post.user.username) %></small>


      <% if signed_in? and @current_user.is_admin? %>
        <small>
        |
        <%= link_to 'Edit',   blog_post_edit_path(:id => @post.id) %> - 
        <%= link_to 'Delete', blog_post_destroy_path(:id => @post.id), :data => { :confirm => 'Are you sure?' } %>
        </small>
      <% end %>
      </div>
      
      <div class="body">
        <%=raw @post.parse! %>
      </div>

      <div class="share">
        <h2>Share</h2>
        <%= link_to image_tag("icons/facebook.png"),   "http://www.facebook.com/sharer.php?u=#{request.original_url}", { :target => '_blank', :title => 'Share on Facebook' } %>
        <%= link_to image_tag("icons/twitter.png"),    "http://twitter.com/home?status=#{@post.category.title.gsub(/#/, '%23')} - #{@post.title} #{request.original_url}", { :target => '_blank', :title => 'Post to Twitter' } %>
        <%= link_to image_tag("icons/googleplus.png"), "https://plus.google.com/share?url=#{request.original_url}", { :target => '_blank', :title => 'Post to Google+' } %>
        <%= link_to image_tag("icons/reddit.png"),     "http://www.reddit.com/submit?url=#{request.original_url}&title=#{@post.category.title} - #{@post.title}", { :target => '_blank', :title => 'Post to Reddit' } %>
      </div>
    </div>

    <%= render :partial => 'comments/box', :locals => { object: @post } %>
    
  </div>
  <%= render :partial => 'layouts/sidebar' %>  
</section>