config/routes.rb
EmoticodeRails::Application.routes.draw do
  root 'home#index'

  namespace :api do
    namespace :v1 do
      
      controller :sources do
        post 'sources/new' => :create, as: :create_source
      end
      # resources :languages, :only => [ :index, :show ]
      # resources :sources
      # resources :users,     :only => [ :index, :show ]
    end
  end

  namespace :blog do
    root 'index#show'

    controller :categories do
      get ':category' => :archive, as: :archive, constraints: { category: Patterns::ROUTE_PATTERN }
    end

    controller :posts do
      get  ':category/:name.html' => :show, as: :show_post, constraints: { category: Patterns::ROUTE_PATTERN, name: Patterns::ROUTE_PATTERN }      
      get  ':category/new'        => :new,  as: :new_post, constraints: { category: Patterns::ROUTE_PATTERN }
      post ':category/create'     => :create,  as: :create_post, constraints: { category: Patterns::ROUTE_PATTERN }

      get   'post/edit/:id'    => :edit,    as: :post_edit,    constraints: { id: Patterns::ID_PATTERN }
      get   'post/destroy/:id' => :destroy, as: :post_destroy, constraints: { id: Patterns::ID_PATTERN }
      patch 'post/update/:id'  => :update,  as: :post_update,  constraints: { id: Patterns::ID_PATTERN }
    end
  end

  controller :home do
    get 'new'      => :recent,   as: :recent_snippets
    get 'trending' => :trending, as: :trending_snippets
  end

  controller :sitemaps do
    get 'sitemap_index'          => :index,     as: :sitemap_index
    get 'sitemap_snippets-:page' => :snippets,  as: :sitemap_snippets, constraints: { page: Patterns::ID_PATTERN }
    get 'sitemap_languages'      => :languages, as: :sitemap_languages
    get 'sitemap_posts'          => :posts,     as: :sitemap_posts
  end

  controller :sessions do
    get    'sign_in'  => :new,     as: :sign_in
    post   'sign_in'  => :create
    delete 'sign_out' => :destroy, as: :sign_out
  end

  controller :user do
    get  'sign_up'        => :new,     as: :sign_up
    post 'sign_up'        => :create
    get  'confirm/:token' => :confirm, as: :confirm, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  get '/auth/:provider/callback' => 'sessions#create'

  controller :favorite do
    post 'fav/:id'   => :make,    as: :favorite,   constraints: { id: Patterns::ID_PATTERN }
    post 'unfav/:id' => :destroy, as: :unfavorite, constraints: { id: Patterns::ID_PATTERN }
  end

  controller :follows do
    post 'follow/:type/:id'   => :follow,   as: :follow,   constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }
    post 'unfollow/:type/:id' => :unfollow, as: :unfollow, constraints: { type: Patterns::ID_PATTERN, id: Patterns::ID_PATTERN }    
  end

  controller :profile do
    get   'profile/snippets'    => :snippets,  as: :user_snippets
    get   'profile/favorites'   => :favorites, as: :user_favorites   
    get   'profile/edit'        => :edit, as: :user_settings
    patch 'profile/update'      => :update
    get   'profile/:username'   => :show, as: :user_profile, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/:username/following' => :following, as: :user_following, constraints: { username: Patterns::USERNAME_PATTERN }
    get   'profile/:username/followers' => :followers, as: :user_followers, constraints: { username: Patterns::USERNAME_PATTERN }    
    get   'profile/destroy/:id' => :destroy, as: :user_delete, constraints: { id: Patterns::ID_PATTERN }
    get   'profile/ban/:id'     => :ban, as: :user_ban, constraints: { id: Patterns::ID_PATTERN }    
    get   'profile/unban/:id'   => :unban, as: :user_unban, constraints: { id: Patterns::ID_PATTERN }        
    get   'badge/:username'     => :badge, as: :user_badge, constraints: { username: Patterns::USERNAME_PATTERN }
  end

  controller :search do
    get 'search(/:what)' => :search, as: :search, :constraints => {:what => /.*/}
  end

  resource :comments
  resource :votes

  resource :passwords, :only => [:new, :create]
  controller :passwords do
    get  'recovery/:token' => :edit, as: :recovery, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
    post 'recovery/:token' => :update, constraints: { token: Patterns::CONFIRMATION_TOKEN_PATTERN }
  end

  controller :feeds do
    get 'feed'                   => :feed,     as: :feed
    get '/stream/:username'      => :stream,   as: :stream_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'feed/blog'              => :blog,     as: :blog_feed
    get 'feed/:language'         => :language, as: :language_feed, constraints: { language: Patterns::ROUTE_PATTERN }
    get 'profile/:username/feed' => :user,     as: :user_feed, constraints: { username: Patterns::USERNAME_PATTERN }
    get 'randomfeed'             => :random,   as: :random_feed
  end

  controller :page do
    get  'about.html'   => :about,   as: :about_page
    get  'sitemap.html' => :sitemap, as: :sitemap_page
    get  'contact.html' => :contact, as: :contact_page
  end

  controller :language do
    get ':name/',    to: :archive, as: :language_archive, constraints: { name: Patterns::ROUTE_PATTERN }
  end

  controller :source do
    get   'source/new'         => :new,     as: :source_new
    post  'source/create'      => :create,  as: :source_create
    get   'source/edit/:id'    => :edit,    as: :source_edit,   constraints: { id: Patterns::ID_PATTERN }
    get   'source/destroy/:id' => :destroy, as: :source_delete, constraints: { id: Patterns::ID_PATTERN }
    patch 'source/update/:id'  => :update,  as: :source_update, constraints: { id: Patterns::ID_PATTERN }

    get 'source/:id'                             => :show,  as: :source_shortlink,     constraints: { id: Patterns::ID_PATTERN }
    get ':language_name/:source_name.html'       => :show,  as: :source_with_language, constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get ':language_name/:source_name.txt'        => :raw,   as: :raw_with_language,    constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }
    get 'embed/:language_name/:source_name.html' => :embed, as: :source_embed,         constraints: { language_name: Patterns::ROUTE_PATTERN, source_name: Patterns::ROUTE_PATTERN }    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !@current_user.nil?
      @sources = @current_user.stream params[:page]
      @cloud   = Tag.cloud.shuffle!
    else
      pager_params = { :page => params[:page], :per_page => 16, :include => :language }

      @sources = Source.public.by_trend.newer_than( 2.months.ago.to_i ).paginate pager_params
      @cloud   = Tag.cloud.shuffle!
    end
  end

  def trending
    pager_params = { :page => params[:page], :per_page => 16, :include => :language }

    @sources = Source.public.by_trend.newer_than( 2.months.ago.to_i ).paginate pager_params
    @cloud   = Tag.cloud.shuffle!
  end

  def recent
    pager_params = { :page => params[:page], :per_page => 16, :include => :language }
    
    @recent  = Source.public.paginate pager_params
    @cloud   = Tag.cloud.shuffle!    
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def page_title
    paged "#{super} | #{controller.action_name.capitalize}"
  end
end

app/views/home/_heading.html.erb
<section id="heading">
  <div class="motto">Discover a whole new concept of source code.</div>
  <div class="submotto">Search on over 50.000 code snippets!</div>

  <form method="get" action="/search/"> 
    <input type="text" x-webkit-speech name="what">
  </form>
</section>

<section id="ruler">
  <div class="inner">
    <div class="tabber">
      <% if signed_in? %>

        <% if current_page?(root_url) %>
          <%= link_to '<i class="icon-rss"></i>'.html_safe, stream_feed_url(:username => @current_user.username), :title => 'Your stream feed', :class => 'rss', :id => 'streamfeed' %>
        <% end %>

        <h3 class="tab">
          <%= link_to 'Stream', root_path, :class => current_page?(root_url) ? 'current' : '' %>
        </h3>
        <h3 class="tab">
          <%= link_to 'Trending', trending_snippets_path, :class => current_page?(trending_snippets_url) ? 'current' : '' %>
        </h3>
      <% else %>
        <h3 class="tab">
          <%= link_to 'Trending', root_path, :class => current_page?(root_url) ? 'current' : '' %>
        </h3>
      <% end %>
      <h3 class="tab">
        <%= link_to 'Recent', recent_snippets_path, :class => current_page?(recent_snippets_url) ? 'current' : '' %>
      </h3>
    </div>
    <div class="small-column">
      
    </div>
  </div>
</section>

app/views/home/index.html.erb
<section id="home">
  <% if signed_in? and @sources.empty? %>
    <div id="startfollowing">
      Welcome to your personal stream, start following your favorite users or a whole language channel using the <span class="follow"><a href="#" onclick="return false;" class="follow">Follow</a></span> 
      buttons you will find around the website.<br/><br/>
      <center>
        Wanna give it a try?
        <span class="follow">
          <% user = User.find_by_username 'evilsocket' %>
          <% if @current_user.follows?(user) %>
            <%= link_to "Following #{user.username}", unfollow_path( type: Follow::TYPES[:user], id: user.id, format: :js ), :'data-subject' => user.username, class: "follow-#{Follow::TYPES[:user]}-#{user.id} following", method: :post, remote: true  %>
          <% else %>
            <%= link_to "Follow #{user.username}", follow_path( type: Follow::TYPES[:user], id: user.id, format: :js ), :'data-subject' => user.username, class: "follow-#{Follow::TYPES[:user]}-#{user.id} follow", method: :post, remote: true  %>
          <% end %>
        </span> and <%= link_to 'refresh', root_url %> this page, you can edit your followings anytime in your <%= link_to( 'profile', user_following_path(username:@current_user.username) ) %> page.
    </center> 
    </div>
  <% else %>
    <ul class="listing">
      <%= render :partial => "source/listing", :collection => @sources, :as => 'source' %>
    </ul>
  <% end %>

  <%= render :partial => 'layouts/sidebar', :locals => { with_heading: false } %>
</section>

<br style="clear:both"/>

<section class="pager">
  <%= will_paginate @sources %>
</section>

app/views/home/recent.html.erb
<section id="home">
  <ul class="listing">
    <%= render :partial => "source/listing", :collection => @recent, :as => 'source' %>
  </ul>
  <%= render :partial => 'layouts/sidebar', :locals => { with_heading: false } %>
</section>

<br style="clear:both"/>

<section class="pager">
  <%= will_paginate @recent %>
</section>

app/views/home/trending.html.erb
<section id="home">
  <ul class="listing">
    <%= render :partial => "source/listing", :collection => @sources, :as => 'source' %>
  </ul>
  <%= render :partial => 'layouts/sidebar', :locals => { with_heading: false } %>
</section>

<br style="clear:both"/>

<section class="pager">
  <%= will_paginate @sources %>
</section>